apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TouchpointPlatformConsole
  tags:
    - automation
    - btp
    - touchpoint
    - assembly
  annotations:
    backstage.io/adr-location: docs/adr
spec:
  type: website
  owner: group:Promptus
  lifecycle: experimental
  system: TouchpointAutomation
